# Generated by Django 5.0 on 2026-07-14 23:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parcelas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especie', models.CharField(choices=[('maiz', 'Maíz'), ('frijol', 'Frijol'), ('sorgo', 'Sorgo'), ('tomate', 'Tomate'), ('chile', 'Chile'), ('mango', 'Mango'), ('aguacate', 'Aguacate'), ('cana', 'Caña de azúcar'), ('limon', 'Limón'), ('naranja', 'Naranja'), ('pepino', 'Pepino'), ('calabaza', 'Calabaza'), ('otro', 'Otro')], max_length=30)),
                ('variedad', models.CharField(blank=True, max_length=100)),
                ('fecha_siembra', models.DateField()),
                ('fecha_cosecha_esperada', models.DateField(blank=True, null=True)),
                ('fecha_cosecha_real', models.DateField(blank=True, null=True)),
                ('rendimiento_ton_ha', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('precio_venta_ton', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estado', models.CharField(choices=[('planificado', 'Planificado'), ('siembra', 'En siembra'), ('desarrollo', 'En desarrollo'), ('floracion', 'En floración'), ('cosecha', 'Listo para cosecha'), ('finalizado', 'Finalizado')], default='planificado', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('parcela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cultivos', to='parcelas.parcela')),
            ],
            options={
                'ordering': ['-fecha_siembra'],
            },
        ),
    ]
