# Generated by Django 5.0 on 2026-07-14 23:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cultivos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AplicacionInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('fertilizante', 'Fertilizante'), ('herbicida', 'Herbicida'), ('insecticida', 'Insecticida'), ('fungicida', 'Fungicida'), ('riego', 'Riego'), ('otro', 'Otro')], max_length=20)),
                ('nombre_producto', models.CharField(max_length=150)),
                ('fecha_aplicacion', models.DateField()),
                ('dosis_por_ha', models.DecimalField(decimal_places=2, max_digits=8)),
                ('unidad_dosis', models.CharField(max_length=20)),
                ('costo_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aplicaciones', to='cultivos.cultivo')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_aplicacion'],
            },
        ),
    ]
